# Generated by Django 5.2.15 on 2026-06-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyWorkingDays',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('working_days', models.IntegerField()),
            ],
        ),
    ]
